dns:
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8    
    - 8.8.4.4    
  nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
    - "https://doh.360.cn/dns-query"
  nameserver-policy:
    geosite:cn:
      - "https://dns.alidns.com/dns-query"
      - "https://doh.pub/dns-query"
      - "https://doh.360.cn/dns-query"
    geosite:geolocation-!cn:
      - "https://1.1.1.1/dns-query"
      - "https://8.8.8.8/dns-query"
  fallback:
    - "https://1.1.1.1/dns-query"
    - "https://8.8.8.8/dns-query"
    - "https://doh.dns.sb/dns-query"
    - "https://dns.cloudflare.com/dns-query"
    - "https://1.0.0.1/dns-query"
    - "https://public.dns.iij.jp/dns-query"   
    - "https://dns.twnic.tw/dns-query"
    - "tls://8.8.4.4:853"
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
  fake-ip-filter:
#Epicor
    - "+.epicor.com"
    - "+.epicorsaas.com"
    - "+.scorm.com"
    - "+.brightcove.net"
#Google应用商店
    - "+.services.googleapis.cn"
    - "+.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "+.gstatic.com"
    - "+.clientservices.googleapis.com"
rules:
  - "SRC-IP-CIDR,192.168.18.240/32,DIRECT"
  - "SRC-IP-CIDR,192.168.18.188/32,DIRECT"
  - "DST-PORT,6071,DIRECT"
  - "SRC-PORT,6071,DIRECT"
  - "DOMAIN-SUFFIX,wolai.com,DIRECT"
  - "DOMAIN-SUFFIX,epicorsaas.com,DIRECT"
  - "DOMAIN-KEYWORD,evision.lhkpoc.com,DIRECT"
  - "DOMAIN-KEYWORD,vm1.pov.local,DIRECT"
  - "IP-CIDR,20.24.81.132/32,DIRECT"
