dns:
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8    
    - 8.8.4.4    
  nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
    - "https://doh.360.cn/dns-query"
  nameserver-policy:
   # google ä¼˜å…ˆä½¿ç”¨å›½å¤– dns å’Œä¸‹é¢çš„ä»£ç†è§„åˆ™ä¸€è‡´ï¼Œå¯ä»¥è§£å†³play æ— æ³•ä¸‹è½½é—®é¢˜ï¼Œå¦åˆ™ä¼šè¢«ä¸‹é¢çš„ cn list åŒ¹é…ä½¿ç”¨å›½å†… dns è§£æåˆ°é”™è¯¯ ip
     geosite:google:
     - "tls://8.8.4.4"
     - "tls://1.1.1.1"
   # å›½å†…
    geosite:private,onedrive,microsoft@cn,apple,category-games@cn,cn:
    # geosite:cn:
      - 223.5.5.5
      - 119.29.29.29
      - 114.114.174.114
      # - "https://dns.alidns.com/dns-query"
      # - "https://doh.pub/dns-query"
      - "https://doh.360.cn/dns-query"
    #å›½å¤–
    geosite:geolocation-!cn:
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
      # - "https://1.1.1.1/dns-query"
      # - "https://8.8.8.8/dns-query"
  fallback:
    - "https://1.1.1.1/dns-query"
    - "https://8.8.8.8/dns-query"
    - "https://doh.dns.sb/dns-query"
    - "https://dns.cloudflare.com/dns-query"
    - "https://1.0.0.1/dns-query"
    - "https://public.dns.iij.jp/dns-query"   
    - "https://dns.twnic.tw/dns-query"
    - "tls://8.8.4.4:853"
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
  fake-ip-filter:
#Epicor
    - "+.epicor.com"
    - "+.epicorsaas.com"
    - "+.scorm.com"
    - "+.scorm.net"    
    - "+.brightcove.net"
    - "+.brightcove.com"
    - "+.evision.lhkpoc.com"
    - "+.vm1.pov.local"    
#Googleåº”ç”¨å•†åº—
    - "+.services.googleapis.cn"
    - "+.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "+.gstatic.com"
    - "+.clientservices.googleapis.com"
sub-rules:
  ipv6:
    - GEOSITE,cn,DIRECT
    - GEOSITE,microsoft,DIRECT
    - GEOSITE,apple,DIRECT
    - GEOSITE,steam,DIRECT    
    - DOMAIN-SUFFIX,local,DIRECT    
    - GEOIP,private,DIRECT
    - GEOIP,CN,DIRECT
    - MATCH,ğŸ”°å›½å¤–æµé‡(IPV6)
